parent: "configs/ours_base.yaml"
save_step: 400

frame_start: 0
frame_step: 0
frame_num: -1

# dataset params:
verbose: True
source_path: "/yifan-vol/rtg-slam/data/Ours/hotel"
save_path: "/yifan-vol/rtg-slam/output/dataset/Ours/hotel"

use_gt_pose: False