parent: "configs/ours_base.yaml"
save_step: 1

frame_start: 0
frame_step: 0
frame_num: -1

# dataset params:
type: "AVL"
verbose: True
source_path: "/yifan-vol/rtg-slam/data/avl/04042023/cam6"
save_path: "/yifan-vol/rtg-slam/output/avl/04042023/gt_pose/cam6_640x480_20k_sky-car-human-road_cut_2/trans_thes_1"

use_gt_pose: True
use_orb_backend: False
icp_use_model_depth: False # if False, use dataset depth frame to frame
orb_settings_path: "configs/orb_config/avl.yaml"
# unstable_time_window: 200

uniform_sample_num: 20000
max_depth: 80
keyframe_trans_thes: 1
# pcd_densify: True